#DEFINE	pcvCARR_COL_ID	        	1
#DEFINE	pcvCARR_COL_CASH_NUMBER		2
#DEFINE	pcvCARR_COL_NM	        	3
#DEFINE	pcvCARR_COL_EXCH_DIR_IN		4
#DEFINE	pcvCARR_COL_EXCH_DIR_OUT	5
#DEFINE	pcvCARR_COL_USE_FOR_UPLOAD	6
#DEFINE	pcvCARR_COL_CNT			6

#DEFINE	pcvMSG_GLOB_ERR		1
#DEFINE	pcvMSG_DETL_ERR		2
#DEFINE	pcvMSG_GLOB_INF		4
#DEFINE	pcvMSG_DETL_INF		8

#DEFINE	pcvBAR_ERR_UNDIG	1
#DEFINE	pcvBAR_ERR_CHKSUM	2
#DEFINE	pcvBAR_ERR_U_TYPE	3

#DEFINE	pcvSRV_ERR_CRITICAL	1
#DEFINE	pcvBAR_ERR_APPLY	2
