&& константы флагов параметров
#DEFINE	FLG_CLK_SOUND			 1
#DEFINE	FLG_LOCALMODE			 2
#DEFINE	FLG_SOFTCONTROL			 4
#DEFINE	FLG_PERSIST				 8

&& константы флагов текущего состояния
#DEFINE	FLG_STATE_LOCALMODE		 1


&& Константы запросов
#DEFINE	REQ_BLOCK				 0x04
#DEFINE	REQ_RESET				 0x05

#DEFINE	REQ_GET_COMMPARAM		 0x1A
#DEFINE	REQ_SET_COMMPARAM		 0x1B

#DEFINE	REQ_GET_PWRPARAM		 0x40
#DEFINE	REQ_SET_PWRPARAM		 0x41
#DEFINE	REQ_ON_CHANELS			 0x42
#DEFINE	REQ_OFF_CHANELS			 0x43
#DEFINE	REQ_ON_CHANEL			 0x44
#DEFINE	REQ_OFF_CHANEL			 0x45
#DEFINE	REQ_SET_CHANELS			 0x46
#DEFINE	REQ_GET_CHANELS			 0x47
#DEFINE	REQ_GET_STATE			 0x48
#DEFINE	REQ_SET_STATE			 0x49


&& Костанты ошибок
#DEFINE	pwrERROR_NO_ERROR			 0
#DEFINE	pwrERROR_INV_UNSUPPORTED	 150
#DEFINE	pwrERROR_INV_PARAM			 151
#DEFINE	pwrERROR_INV_FORMAT			 152
